### ISSUE TITLE
aws ecr get-login command executed with wrong region

### ISSUE THREAD

**Issue by rozhok** [gilt/sundial#18]
Since ECR available only in `us-east-1` region at the moment, this region should be explicitly passed into `aws ecr get-login` command params.

**Comment by rozhok** [comment]
Missed that `REGION` param was set to `us-east-1` by default. However, I think it would be nice to add clarifying comments.

**Comment by rozhok** [comment]
By the way Amazon silently released ECR support in almost all regions so this is not actual anymore

**Comment by kevinoriordan** [comment]
Ah, brilliant.
