### ISSUE TITLE
sample post to create new job does not work

### ISSUE THREAD

**Issue by brandon-dacrib** [gilt/sundial#59]
from this doc: https://github.com/gilt/sundial/blob/master/docs/JOBS.md, "POST this job template to http://sundialurl/api/process_definitions/SampleProcessName" returns action not found For request 'POST /api/process_definitions/SampleProcessName'

**Comment by nemo83** [comment]
Looking at:

https://github.com/gilt/sundial/blob/master/conf/routes#L29

It should be a PUT I think. 

Can you try and let us know? 

Thanks,
Gio

**Comment by nemo83** [comment]
Also, you may need to specify the content type.

**Comment by nemo83** [comment]
Last but not the least, the api has recently changed and you may also need an additional bit in the `subscriptions` json object:

```json
 "subscriptions": [
    {"name": "Cerebro Dev", "email": "cerebro-dev@gilt.com", "notify_when": "on_state_change_and_failures"}
  ],
```

**Comment by brandon-dacrib** [comment]
I got an error but I have been told to put this down and look at another scheduler for now. I did add a pull request to update the documentation.
